<?php

namespace Database\Seeders;

use App\Models\Category;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;


class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {

        Schema::disableForeignKeyConstraints();
        Category::truncate();

        Category::insert([
            
            // 1
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Household Festival',
        		'url' => Str::slug('Household Festival'),
        		'description' => '<p>Coolest collection is available</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => Str::slug('Household Festival'),
                'meta_keywords' => Str::slug('Household Festival'),
                'meta_description' => Str::slug('Household Festival'),
                'search_keywords' => Str::slug('Household Festival'),
                'creator' => '1',
        		'slug' => Str::slug('Household Festival'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],


            // 2
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'RFL Houseware Offer',
        		'url' => Str::slug('RFL Houseware Offer'),
        		'description' => '<p>Coolest collection is available</p>',
                'parent_id' => 1,
                'category_image' => null,
                'page_title' => Str::slug('RFL Houseware Offer'),
                'meta_keywords' => Str::slug('RFL Houseware Offer'),
                'meta_description' => Str::slug('RFL Houseware Offer'),
                'search_keywords' => Str::slug('RFL Houseware Offer'),
                'creator' => '1',
        		'slug' => Str::slug('RFL Houseware Offer'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 3
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Italiano Melamine Offer',
        		'url' => Str::slug('Italiano Melamine Offer'),
        		'description' => '<p>Coolest collection is available</p>',
                'parent_id' => 1,
                'category_image' => null,
                'page_title' => Str::slug('Italiano Melamine Offer'),
                'meta_keywords' => Str::slug('Italiano Melamine Offer'),
                'meta_description' => Str::slug('Italiano Melamine Offer'),
                'search_keywords' => Str::slug('Italiano Melamine Offer'),
                'creator' => '1',
        		'slug' => Str::slug('Italiano Melamine Offer'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 4
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Food & Grocery',
        		'url' => Str::slug('Food & Grocery'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => Str::slug('Food & Grocery'),
                'meta_keywords' => Str::slug('Food & Grocery'),
                'meta_description' => Str::slug('Food & Grocery'),
                'search_keywords' => Str::slug('Food & Grocery'),
                'creator' => '1',
        		'slug' => Str::slug('Food & Grocery'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 5
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Groceries',
        		'url' => Str::slug('Groceries'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 4,
                'category_image' => null,
                'page_title' => Str::slug('Groceries'),
                'meta_keywords' => Str::slug('Groceries'),
                'meta_description' => Str::slug('Groceries'),
                'search_keywords' => Str::slug('Groceries'),
                'creator' => '1',
        		'slug' => Str::slug('Groceries'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 6
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Eggs',
        		'url' => Str::slug('Eggs'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 5,
                'category_image' => null,
                'page_title' => Str::slug('Eggs'),
                'meta_keywords' => Str::slug('Eggs'),
                'meta_description' => Str::slug('Eggs'),
                'search_keywords' => Str::slug('Eggs'),
                'creator' => '1',
        		'slug' => Str::slug('Eggs'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 7
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Oil',
        		'url' => Str::slug('Oil'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 5,
                'category_image' => null,
                'page_title' => Str::slug('Oil'),
                'meta_keywords' => Str::slug('Oil'),
                'meta_description' => Str::slug('Oil'),
                'search_keywords' => Str::slug('Oil'),
                'creator' => '1',
        		'slug' => Str::slug('Oil'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 8
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Rice',
        		'url' => Str::slug('Rice'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 5,
                'category_image' => null,
                'page_title' => Str::slug('Rice'),
                'meta_keywords' => Str::slug('Rice'),
                'meta_description' => Str::slug('Rice'),
                'search_keywords' => Str::slug('Rice'),
                'creator' => '1',
        		'slug' => Str::slug('Rice'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 9
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Flour',
        		'url' => Str::slug('Flour'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 5,
                'category_image' => null,
                'page_title' => Str::slug('Flour'),
                'meta_keywords' => Str::slug('Flour'),
                'meta_description' => Str::slug('Flour'),
                'search_keywords' => Str::slug('Flour'),
                'creator' => '1',
        		'slug' => Str::slug('Flour'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 10
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Spice & Ready Mix',
        		'url' => Str::slug('Spice & Ready Mix'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 5,
                'category_image' => null,
                'page_title' => Str::slug('Spice & Ready Mix'),
                'meta_keywords' => Str::slug('Spice & Ready Mix'),
                'meta_description' => Str::slug('Spice & Ready Mix'),
                'search_keywords' => Str::slug('Spice & Ready Mix'),
                'creator' => '1',
        		'slug' => Str::slug('Spice & Ready Mix'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 11
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Napkins & Tissue Papers',
        		'url' => Str::slug('Napkins & Tissue Papers'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 5,
                'category_image' => null,
                'page_title' => Str::slug('Napkins & Tissue Papers'),
                'meta_keywords' => Str::slug('Napkins & Tissue Papers'),
                'meta_description' => Str::slug('Napkins & Tissue Papers'),
                'search_keywords' => Str::slug('Napkins & Tissue Papers'),
                'creator' => '1',
        		'slug' => Str::slug('Napkins & Tissue Papers'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 12
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Lentil(Dal)',
        		'url' => Str::slug('Lentil'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 5,
                'category_image' => null,
                'page_title' => Str::slug('Lentil'),
                'meta_keywords' => Str::slug('Lentil'),
                'meta_description' => Str::slug('Lentil'),
                'search_keywords' => Str::slug('Lentil'),
                'creator' => '1',
        		'slug' => Str::slug('Lentil'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 13
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Salt, Malasses & Sugar',
        		'url' => Str::slug('Salt, Malasses & Sugar'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 5,
                'category_image' => null,
                'page_title' => Str::slug('Salt, Malasses & Sugar'),
                'meta_keywords' => Str::slug('Salt, Malasses & Sugar'),
                'meta_description' => Str::slug('Salt, Malasses & Sugar'),
                'search_keywords' => Str::slug('Salt, Malasses & Sugar'),
                'creator' => '1',
        		'slug' => Str::slug('Salt, Malasses & Sugar'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 14
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Cleaning Supplies',
        		'url' => Str::slug('Cleaning Supplies'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 5,
                'category_image' => null,
                'page_title' => Str::slug('Cleaning Supplies'),
                'meta_keywords' => Str::slug('Cleaning Supplies'),
                'meta_description' => Str::slug('Cleaning Supplies'),
                'search_keywords' => Str::slug('Cleaning Supplies'),
                'creator' => '1',
        		'slug' => Str::slug('Cleaning Supplies'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 15
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Food Aditives',
        		'url' => Str::slug('Food Aditives'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 5,
                'category_image' => null,
                'page_title' => Str::slug('Food Aditives'),
                'meta_keywords' => Str::slug('Food Aditives'),
                'meta_description' => Str::slug('Food Aditives'),
                'search_keywords' => Str::slug('Food Aditives'),
                'creator' => '1',
        		'slug' => Str::slug('Food Aditives'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 16
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Vinegars',
        		'url' => Str::slug('Vinegars'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 5,
                'category_image' => null,
                'page_title' => Str::slug('Vinegars'),
                'meta_keywords' => Str::slug('Vinegars'),
                'meta_description' => Str::slug('Vinegars'),
                'search_keywords' => Str::slug('Vinegars'),
                'creator' => '1',
        		'slug' => Str::slug('Vinegars'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 17
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Snacks',
        		'url' => Str::slug('Snacks'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => Str::slug('Snacks'),
                'meta_keywords' => Str::slug('Snacks'),
                'meta_description' => Str::slug('Snacks'),
                'search_keywords' => Str::slug('Snacks'),
                'creator' => '1',
        		'slug' => Str::slug('Snacks'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 18
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Bread & Bakery',
        		'url' => Str::slug('Bread & Bakery'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => Str::slug('Bread & Bakery'),
                'meta_keywords' => Str::slug('Bread & Bakery'),
                'meta_description' => Str::slug('Bread & Bakery'),
                'search_keywords' => Str::slug('Bread & Bakery'),
                'creator' => '1',
        		'slug' => Str::slug('Bread & Bakery'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 19
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Dairy',
        		'url' => Str::slug('Dairy'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => Str::slug('Dairy'),
                'meta_keywords' => Str::slug('Dairy'),
                'meta_description' => Str::slug('Dairy'),
                'search_keywords' => Str::slug('Dairy'),
                'creator' => '1',
        		'slug' => Str::slug('Dairy'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 20
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Confectionery',
        		'url' => Str::slug('Confectionery'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => Str::slug('Confectionery'),
                'meta_keywords' => Str::slug('Confectionery'),
                'meta_description' => Str::slug('Confectionery'),
                'search_keywords' => Str::slug('Confectionery'),
                'creator' => '1',
        		'slug' => Str::slug('Confectionery'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 21
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Breakfast',
        		'url' => Str::slug('Breakfast'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => Str::slug('Breakfast'),
                'meta_keywords' => Str::slug('Breakfast'),
                'meta_description' => Str::slug('Breakfast'),
                'search_keywords' => Str::slug('Breakfast'),
                'creator' => '1',
        		'slug' => Str::slug('Breakfast'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 22
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Fruits & Vegetables',
        		'url' => Str::slug('Fruits & Vegetables'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => Str::slug('Fruits & Vegetables'),
                'meta_keywords' => Str::slug('Fruits & Vegetables'),
                'meta_description' => Str::slug('Fruits & Vegetables'),
                'search_keywords' => Str::slug('Fruits & Vegetables'),
                'creator' => '1',
        		'slug' => Str::slug('Fruits & Vegetables'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 23
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Meat & Fish',
        		'url' => Str::slug('Meat & Fish'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => Str::slug('Meat & Fish'),
                'meta_keywords' => Str::slug('Meat & Fish'),
                'meta_description' => Str::slug('Meat & Fish'),
                'search_keywords' => Str::slug('Meat & Fish'),
                'creator' => '1',
        		'slug' => Str::slug('Meat & Fish'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 24
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Fresh Fruits',
        		'url' => Str::slug('Fresh Fruits'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => Str::slug('Fresh Fruits'),
                'meta_keywords' => Str::slug('Fresh Fruits'),
                'meta_description' => Str::slug('Fresh Fruits'),
                'search_keywords' => Str::slug('Fresh Fruits'),
                'creator' => '1',
        		'slug' => Str::slug('Fresh Fruits'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 25
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Dry Fruits',
        		'url' => Str::slug('Dry Fruits'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => Str::slug('Dry Fruits'),
                'meta_keywords' => Str::slug('Dry Fruits'),
                'meta_description' => Str::slug('Dry Fruits'),
                'search_keywords' => Str::slug('Dry Fruits'),
                'creator' => '1',
        		'slug' => Str::slug('Dry Fruits'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 26
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Chocolates & Candies',
        		'url' => Str::slug('Chocolates & Candies'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 0,
                'category_image' => null,
                'page_title' => Str::slug('Chocolates & Candies'),
                'meta_keywords' => Str::slug('Chocolates & Candies'),
                'meta_description' => Str::slug('Chocolates & Candies'),
                'search_keywords' => Str::slug('Chocolates & Candies'),
                'creator' => '1',
        		'slug' => Str::slug('Chocolates & Candies'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 27
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Noodles & Macaroni',
        		'url' => Str::slug('Noodles & Macaroni'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 17,
                'category_image' => null,
                'page_title' => Str::slug('Noodles & Macaroni'),
                'meta_keywords' => Str::slug('Noodles & Macaroni'),
                'meta_description' => Str::slug('Noodles & Macaroni'),
                'search_keywords' => Str::slug('Noodles & Macaroni'),
                'creator' => '1',
        		'slug' => Str::slug('Noodles & Macaroni'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 28
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Sauces',
        		'url' => Str::slug('Sauces'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 17,
                'category_image' => null,
                'page_title' => Str::slug('Sauces'),
                'meta_keywords' => Str::slug('Sauces'),
                'meta_description' => Str::slug('Sauces'),
                'search_keywords' => Str::slug('Sauces'),
                'creator' => '1',
        		'slug' => Str::slug('Sauces'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 29
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Cereal',
        		'url' => Str::slug('Cereal'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 17,
                'category_image' => null,
                'page_title' => Str::slug('Cereal'),
                'meta_keywords' => Str::slug('Cereal'),
                'meta_description' => Str::slug('Cereal'),
                'search_keywords' => Str::slug('Cereal'),
                'creator' => '1',
        		'slug' => Str::slug('Cereal'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 30
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Chips',
        		'url' => Str::slug('Chips'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 17,
                'category_image' => null,
                'page_title' => Str::slug('Chips'),
                'meta_keywords' => Str::slug('Chips'),
                'meta_description' => Str::slug('Chips'),
                'search_keywords' => Str::slug('Chips'),
                'creator' => '1',
        		'slug' => Str::slug('Chips'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 31
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Chips',
        		'url' => Str::slug('Chips-G'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 17,
                'category_image' => null,
                'page_title' => Str::slug('Chips-G'),
                'meta_keywords' => Str::slug('Chips-G'),
                'meta_description' => Str::slug('Chips-G'),
                'search_keywords' => Str::slug('Chips-G'),
                'creator' => '1',
        		'slug' => Str::slug('Chips-G'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 32
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Breads',
        		'url' => Str::slug('Breads'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 18,
                'category_image' => null,
                'page_title' => Str::slug('Breads'),
                'meta_keywords' => Str::slug('Breads'),
                'meta_description' => Str::slug('Breads'),
                'search_keywords' => Str::slug('Breads'),
                'creator' => '1',
        		'slug' => Str::slug('Breads'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 33
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Honey',
        		'url' => Str::slug('Honey'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 18,
                'category_image' => null,
                'page_title' => Str::slug('Honey'),
                'meta_keywords' => Str::slug('Honey'),
                'meta_description' => Str::slug('Honey'),
                'search_keywords' => Str::slug('Honey'),
                'creator' => '1',
        		'slug' => Str::slug('Honey'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 34
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Dessert',
        		'url' => Str::slug('Dessert'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 18,
                'category_image' => null,
                'page_title' => Str::slug('Dessert'),
                'meta_keywords' => Str::slug('Dessert'),
                'meta_description' => Str::slug('Dessert'),
                'search_keywords' => Str::slug('Dessert'),
                'creator' => '1',
        		'slug' => Str::slug('Dessert'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 35
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Cookies',
        		'url' => Str::slug('Cookies'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 18,
                'category_image' => null,
                'page_title' => Str::slug('Cookies'),
                'meta_keywords' => Str::slug('Cookies'),
                'meta_description' => Str::slug('Cookies'),
                'search_keywords' => Str::slug('Cookies'),
                'creator' => '1',
        		'slug' => Str::slug('Cookies'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 36
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Sweetmeat',
        		'url' => Str::slug('Sweetmeat'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 18,
                'category_image' => null,
                'page_title' => Str::slug('Sweetmeat'),
                'meta_keywords' => Str::slug('Sweetmeat'),
                'meta_description' => Str::slug('Sweetmeat'),
                'search_keywords' => Str::slug('Sweetmeat'),
                'creator' => '1',
        		'slug' => Str::slug('Sweetmeat'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 37
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Jelly',
        		'url' => Str::slug('Jelly'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 18,
                'category_image' => null,
                'page_title' => Str::slug('Jelly'),
                'meta_keywords' => Str::slug('Jelly'),
                'meta_description' => Str::slug('Jelly'),
                'search_keywords' => Str::slug('Jelly'),
                'creator' => '1',
        		'slug' => Str::slug('Jelly'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 38
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Vermicellies',
        		'url' => Str::slug('Vermicellies'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 20,
                'category_image' => null,
                'page_title' => Str::slug('Vermicellies'),
                'meta_keywords' => Str::slug('Vermicellies'),
                'meta_description' => Str::slug('Vermicellies'),
                'search_keywords' => Str::slug('Vermicellies'),
                'creator' => '1',
        		'slug' => Str::slug('Vermicellies'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 39
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Milk',
        		'url' => Str::slug('Milk'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 19,
                'category_image' => null,
                'page_title' => Str::slug('Milk'),
                'meta_keywords' => Str::slug('Milk'),
                'meta_description' => Str::slug('Milk'),
                'search_keywords' => Str::slug('Milk'),
                'creator' => '1',
        		'slug' => Str::slug('Milk'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 40
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Ghee & Butter',
        		'url' => Str::slug('Ghee & Butter'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 19,
                'category_image' => null,
                'page_title' => Str::slug('Ghee & Butter'),
                'meta_keywords' => Str::slug('Ghee & Butter'),
                'meta_description' => Str::slug('Ghee & Butter'),
                'search_keywords' => Str::slug('Ghee & Butter'),
                'creator' => '1',
        		'slug' => Str::slug('Ghee & Butter'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 41
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Ghee & Butter',
        		'url' => Str::slug('Ghee & Butter'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 19,
                'category_image' => null,
                'page_title' => Str::slug('Ghee & Butter'),
                'meta_keywords' => Str::slug('Ghee & Butter'),
                'meta_description' => Str::slug('Ghee & Butter'),
                'search_keywords' => Str::slug('Ghee & Butter'),
                'creator' => '1',
        		'slug' => Str::slug('Ghee & Butter'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 42
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Cheese',
        		'url' => Str::slug('Cheese'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 19,
                'category_image' => null,
                'page_title' => Str::slug('Cheese'),
                'meta_keywords' => Str::slug('Cheese'),
                'meta_description' => Str::slug('Cheese'),
                'search_keywords' => Str::slug('Cheese'),
                'creator' => '1',
        		'slug' => Str::slug('Cheese'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 43
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Ice Cream',
        		'url' => Str::slug('Ice Cream'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 19,
                'category_image' => null,
                'page_title' => Str::slug('Ice Cream'),
                'meta_keywords' => Str::slug('Ice Cream'),
                'meta_description' => Str::slug('Ice Cream'),
                'search_keywords' => Str::slug('Ice Cream'),
                'creator' => '1',
        		'slug' => Str::slug('Ice Cream'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],
            // 44
        	[
        		'is_top_category' => 1,
        		'is_home_category' => 1,
        		'is_nav_category' => 1,
        		'name' => 'Yogurt',
        		'url' => Str::slug('Yogurt'),
        		'description' => '<p>Best food and grocery should be your choice</p>',
                'parent_id' => 19,
                'category_image' => null,
                'page_title' => Str::slug('Yogurt'),
                'meta_keywords' => Str::slug('Yogurt'),
                'meta_description' => Str::slug('Yogurt'),
                'search_keywords' => Str::slug('Yogurt'),
                'creator' => '1',
        		'slug' => Str::slug('Yogurt'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
        	],


        ]);

        Schema::enableForeignKeyConstraints();
    }
}
